### PR TITLE
Make shell script to run the setup and test of web application

### PR DESCRIPTION
**Pull request by seiay**
## Description
I made the shell script to run the setup and test of the web application.

## Test-Performed
1. run selenium
2. run the new script in /saint-sorting/

You'll confirm you can run setup and test at one window.

### CODE REVIEW

**Comment by seiay** [comment]
Sorry, I forgot that the previous PR was not merged.
I'll push again later.

So, please wait to review.

**Comment by asana17** [comment]
I think the indent of the zsh script looks so weird (too many spaces). Well, this is not an error, so you don't need to fix it.

**Comment by asana17** [comment]
Can you make a selenium jar file also run by this script?

**Comment by asana17** [comment]
> Sorry, I forgot that the previous PR was not merged. I'll push again later.
> 
> So, please wait to review.

This script may be independent of the previous PR. So you don't need to care about the PR order.

**Comment by seiay** [comment]
> Can you make a selenium jar file also run by this script?

Sorry, I'm late.
I made a selenium jar file also run.

**Comment by asana17** [comment]
I could run with a pre-build Thirtyfour test, but it is necessary to improve in some aspects.

1.  run_with_browser starts before finishing a build of the Thirtyfour test.
2.  The application and the selenium won't stop automatically. They are recommended to be stopped after Ctrl-C.
3.  It is not necessary to open a browser when testing.

**Comment by asana17** [comment]
You can solve the problems above with the following suggestions:

1.  Don't open a browser tab when testing.
2. Check if the build process of the Thirtyfour test is finished by the `ps` command.
3.  Check if a Thirtyfour test process is finished, then kill an application and the selenium.

**Comment by asana17** [comment]
Also, you need to check some cases:

1. when the application and the test are not built (ex. run after `cargo clean`).
2. when a build process failed.
3. when the application (or test, selenium) already running.

**Pull request closed without merging**
